dist: xenial
language: java
jdk:
  - openjdk8
sudo: false

cache:
  directories:
    - $HOME/.m2
    -
install: mvn clean install

# use latest java version available instead of travis default
addons:
  sonarcloud:
    organization: "jacquesmilitello-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.javadoc.skip=true -Dgpg.skip=true